name: "Prettier Check"
description: "Run Prettier on the code"
inputs:
  pathToValidate:
    description: "The path to the files we want to validate"
    required: true
runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
        echo "Path to validate: ${{ inputs.pathToValidate }}"

    - name: Prettier Check
      shell: bash
      run: |
        npx prettier --check --ignore-path .gitignore --ignore-path .prettierignore" ${{ inputs.pathToValidate }}
