name: "Publish artifact"
description: "Publish an artifact to GitHub npm registery"
inputs:
  nodeToken:
    description: "A Github PAT"
    required: true

runs:
  using: composite
  steps:
    - name: "Publish"
      shell: bash
      run: |
        if [ -d "artifacts" ] && [ -n "$(ls -A artifacts)" ]; then
          sfp publish --artifactdir artifacts --npm --scope @${{ github.repository_owner }}  --gittag --pushgittag
        else
          echo "No artifacts to publish"
        fi
      env:
        NODE_AUTH_TOKEN: ${{ inputs.nodeToken }}
