name: "Build and publish artifact"
description: "Build and publish an artifact to github npm registery"
inputs:
  nodeToken:
    description: "A Github PAT"
    required: true

runs:
  using: composite
  steps:
    - name: "Authenticate to npm"
      uses: actions/setup-node@v4
      with:
        registry-url: "https://npm.pkg.github.com"

    - name: "Build package"
      shell: bash
      run: |
        sfp build --devhubalias devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/}

    - name: "Publish"
      shell: bash
      run: |
        sfp publish --artifactdir artifacts --npm --scope @${{ github.repository_owner }}  --gittag --pushgittag
      env:
        NODE_AUTH_TOKEN: ${{ inputs.nodeToken }}

    - uses: navikt/sf-platform/.github/actions/uploadWorkflowArtifactsAndLogs@main
      with:
        artifactName: "build-artifacts"
        uploadArtifacts: true
        logName: "build-logs"
        publishLogs: true
