name: "Install SF CLI"
description: "Check if SF CLI is installed and install if not"
inputs:
  version:
    description: "Version for the SF CLI version"
    default: "latest"
    required: false
runs:
  using: "composite"
  steps:
    # Install SF CLI
    - name: Install SF CLI|
      run: |
        printf 'Checking sf version...\n' >&2
        if ! sf --versionj
        then
          printf 'sf not found, installing...\n' >&2
          npm install --global @salesforce/cli@${{ inputs.version }}
          SFDX_DISABLE_DNS_CHECK=true
        fi

        echo sf version: $(sf --version)

      shell: bash
