name: "Prettier Check"
description: "Run Prettier on the code"
inputs:
  pathToValidate:
    description: "The path to the files we want to validate"
    required: true
runs:
  using: "composite"
  steps:
    - name: Prettier Check
      shell: bash
      run: |
        echo "::group::Run Prettier Check"
        npx prettier --check --ignore-path .gitignore --ignore-path .prettierignore --no-error-on-unmatched-pattern ${{ inputs.pathToValidate }}
        echo "::endgroup::"
