name: "Create Scratch Pool"
description: "Create scratch pools"
inputs:
  devhub:
    description: "Devhub alias or username"
    required: true
  poolConfigPath:
    description: "Path to the pool config file"
    required: true
  nodeToken:
    description: "A Github PAT"
    required: true
runs:
  using: composite
  steps:
    # Authenticate to npm
    - uses: actions/setup-node@v4
      with:
        registry-url: "https://npm.pkg.github.com"

    - name: "Prepare a pool of scratch orgs"
      continue-on-error: true
      shell: bash
      run: |
        echo "poolTag=$(jq --raw-output '.tag' ${{inputs.poolConfigPath}})" >> $GITHUB_ENV

        #Prepare Pool
        sfp pool prepare --poolconfig ${{ inputs.poolConfigPath }} --targetdevhubusername ${{ inputs.devhub }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.nodeToken }}
