name: "Release artifacts"
description: "Release artifacts"
inputs:
  pathToReleaseDef:
    description: "Path to release definition file"
    required: true
  targetOrg:
    description: "Target org username or alias"
    required: true
  nodeToken:
    description: "A Github PAT"
    required: true
runs:
  using: composite
  steps:
    # Release to environment
    - name: "Release to org"
      shell: bash
      run: 'sfp release --targetorg ${{ inputs.targetOrg }} --releasedefinition ${{ inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog --logsgroupsymbol "::group::,::endgroup::"'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.nodeToken }}
