name: "Generate release definitions"
description: "Generate release definitions"
inputs:
  branchToCommitTo:
    description: "Repository branch in which the release definition files are to be written"
    required: true
  gitRef:
    description: "Utilize the tags on the source branch to generate release definiton"
    required: true
  pathToConfigFile:
    description: "Path to release config file"
    required: true
  releaseName:
    description: "Name of the release"
    required: true
  directory:
    description: "Relative path to directory to which the release defintion file should be generated"
    required: false
runs:
  using: composite
  steps:
    # Generate release definition file
    - name: Generate release definition file
      shell: bash
      run: sfp releasedefinition generate --gitref ${{ inputs.gitRef }} --configfile ${{ inputs.pathToConfigFile }} --releasename ${{ inputs.releaseName }} --directory ${{ inputs.directory }} --branchname ${{ inputs.branchToCommitTo }}
