name: "Validate"
description: "Validate build"
inputs:
  devhub:
    description: Username or alias of the dev hub org
    required: true
  pools:
    description: Name of pools to use
    required: true
  baseBranch:
    description: The pull request base branch
    required: false
    default: "main"
  deleteScratch:
    description: Delete scratch org after validation
    required: false
    default: "true"
  packageKey:
    description: Keys to be used while installing any managed package dependencies. Required format is a string of key-value pairs separated by spaces e.g. packageA:key packageB:key
    required: false
  mode:
    description: One of these individual|fastfeedback|thorough|ff-release-config|thorough-release-config
    default: "thorough"
    required: false
  releaseConfig:
    description: (Required if the release modes are ff-relese-config or thorough-release-config), Path to the config file which determines which impacted domains need to be validated
    required: false
  coveragePercent:
    description: Minimum required percentage coverage for validating code coverage of packages with Apex classes
    default: "75"
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: validate
      shell: bash
      run: |
        command="sfp validate --pools ${{ inputs.pools }} --targetdevhubusername ${{ inputs.devhub }} --basebranch ${{ inputs.baseBranch }} --coveragepercent ${{ inputs.coveragePercent }} --mode ${{ inputs.mode }} --logsgroupsymbol "::group::,::endgroup::""

        if [ ${{ inputs.deleteScratch }} ];
        then
          command+=" --deletescratchorg"
        fi

        eval $command
