mutation (
    $clientMutationId: String,
    $pullRequestId: ID!
) {
    convertPullRequestToDraft(
        input: {
            ConvertPullRequestToDraftInput: {
                clientMutationId: $clientMutationId,
                pullRequestId: $pullRequestId
            }
        }
    ) {
        pullRequest{
        id,
        isDraft
        }
    }
}
