name: Push logged metrics
description: Push logged metrics
inputs:
  metricsKey:
    description: Private key for signing messages
    required: true
runs:
  using: composite
  steps:
    - name: Do it
      continue-on-error: true
      shell: bash
      run: |
        if [[ -f .sfpowerscripts/logs/metrics.log ]]; then
          # send some stats whilst we're at it
          echo Metrics file found.
          nl .sfpowerscripts/logs/metrics.log
          countmetrics=$(jq --slurp --raw-output '
            # just keep the last value
            reverse | unique_by(.metric, .tags) | reverse | .[] |
            select(.type == "count") |
            # assume counters with no value given are 1
            (
                if .value == null then 1
                else .value
                end
            ) as $value |
            # only allow alpha, _, and : in metrics name
            (.metric | gsub("[^a-z_]"; ":")) as $metric |
            # transform tags into prometheus
            (.tags // {} | to_entries | map(.key + "=\"" + (.value | tostring) + "\"") | join(",")) as $tags |
            # put it all together. one line with description, one line with metric.
            "# TYPE \($metric) counter\n\($metric){\($tags)} \($value)"
          ' .sfpowerscripts/logs/metrics.log | awk '/^# TYPE / && a[$3]++ {next}; 1')
          gaugemetrics=$(jq --slurp --raw-output '
            # just keep the last value
            reverse | unique_by(.metric, .tags) | reverse | .[] |
            select(.type == "guage" or .type == "timers") |
            # only allow alpha, _, and : in metrics name
            (.metric | gsub("[^a-z_]"; ":")) as $metric |
            # transform tags into prometheus
            (.tags // {} | to_entries | map(.key + "=\"" + (.value | tostring) + "\"") | join(",")) as $tags |
            # put it all together. one line with description, one line with metric.
            "# TYPE \($metric) gauge\n\($metric){\($tags)} \(.value)"
          ' .sfpowerscripts/logs/metrics.log | awk '/^# TYPE / && a[$3]++ {next}; 1')
          echo "METRICSKEY len: ${#METRICSKEY}"
          keyfile=$(mktemp) || exit 1
          cat > "$keyfile" <<< "$METRICSKEY"
          # send count metrics. accumulate by specifying instance per run.
          sig=$(printf %s "$countmetrics" | openssl dgst -sha256 -sign "$keyfile" -out - | base64 -w0)
          jq --compact-output --null-input \
            --arg metrics "$countmetrics" \
            --arg runner sf-platform \
            --arg sig "$sig" \
            '{"runner":$runner,"metrics":$metrics,"signature":$sig}' |
            tee >(curl -D- -H 'Content-Type: application/json' --data-binary @- \
              "https://sf-github-metrics.ekstern.dev.nav.no/measures/job/sfplatform/instance/${{github.run_id}}")
          # send gauge metrics. no instance means metrics sent get overwritten.
          sig=$(printf %s "$gaugemetrics" | openssl dgst -sha256 -sign "$keyfile" -out - | base64 -w0)
          jq --compact-output --null-input \
            --arg metrics "$gaugemetrics" \
            --arg runner sf-platform \
            --arg sig "$sig" \
            '{"runner":$runner,"metrics":$metrics,"signature":$sig}' |
            tee >(curl -D- -H 'Content-Type: application/json' --data-binary @- \
              https://sf-github-metrics.ekstern.dev.nav.no/measures/job/sfplatform)
        else
          echo No metrics file this time.
          ls -laR .sfpowerscripts
        fi
      env:
        METRICSKEY: ${{ inputs.metricsKey }}
