name: "[AUTO LAUNCHED]"
on:
  pull_request:
  push:
concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: ${{ !(github.event_name == 'push' && github.ref_name == 'main') }}
jobs:
  staticCodeValidation:
    name: Validation jobs
    uses: navikt/sf-platform/.github/workflows/ciStaticCodeValidation.yml@main
    permissions:
      contents: read
  buildAndPublish:
    name: Build Jobs
    needs: staticCodeValidation
    uses: navikt/sf-platform/.github/workflows/buildAndPublish.yml@main
    permissions:
      contents: write
      packages: write
    secrets:
      SF_DEVHUB_URL: ${{ secrets.SF_DEVHUB_URL }}
