name: Bump Patch Version of Packages
description: Bump the patch version of specified packages in sfdx-project.json and commit the changes.

on:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Debug GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN is set: ${{ secrets.GITHUB_TOKEN != '' }}"

      - name: Configure Git for signing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get modified package names
        id: get_modified_packages
        run: |
          sfp impact package --basebranch main
          impacted_packages=$(jq -r 'join(",")' impacted-package.json)
          echo "impacted_packages=$impacted_packages" >> "$GITHUB_OUTPUT"

      - uses: navikt/sf-gha-bump-patch-version@main
        if: steps.get_modified_packages.outputs.impacted_packages != ''
        with:
          package_names: ${{ steps.get_modified_packages.outputs.impacted_packages }}

      - uses: navikt/sf-platform/.github/actions/commitFiles@main
        if: steps.get_modified_packages.outputs.impacted_packages != ''
        with:
          files: sfdx-project.json
          commitMessage: "Update package version to $VERSION_NUMBER for $PACKAGE_NAME"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug commit signature
        if: failure() # Run only if previous steps fail
        run: |
          git log --show-signature -1
          echo "Git config:"
          git config --global --list¨
