name: "Quick build"
on:
  push:
    paths:
      - "src/**"
      - "!src/**/*.md"
  workflow_dispatch:
  workflow_call:
    secrets:
      SF_DEVHUB_URL:
        required: true

jobs:
  validateCode:
    uses: navikt/sf-platform/.github/workflows/ciStaticCodeValidation.yml@main

  validatePool:
    needs: validateCode
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest
    permissions:
      contents: read
    steps:
      - uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@master
        with:
          auth-url: ${{ secrets.SF_DEVHUB_URL }}
          alias: "devhub"
          setDefaultDevhubUsername: "true"

      - uses: navikt/sf-platform/.github/actions/ciValidate@main
        with:
          devhub: "devhub"
          pools: "ci"

  quickBuild:
    name: "Quickbuild"
    needs: validatePool
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:${{ vars.SFP_CONTAINER_VERSION }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@master
        with:
          auth-url: ${{ secrets.SF_DEVHUB_URL }}
          alias: devhub
          setDefaultDevhubUsername: true

      - uses: navikt/sf-platform/.github/actions/ciQuickBuild@main
