name: "Quick build"
on:
  push:
    paths:
      - "src/**"
      - "!src/**/*.md"
  workflow_dispatch:
  workflow_call:
    secrets:
      SF_DEVHUB_URL:
        required: true

jobs:
  validate:
    uses: navikt/sf-platform/.github/workflows/ciStaticCodeValidation.yml@main

  quickBuild:
    name: "Quickbuild"
    needs: validate
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - uses: navikt/crm-workflows-base/.github/actions/authenticateOrg@master
        with:
          auth-url: ${{ secrets.SF_DEVHUB_URL }}
          alias: devhub
          setDefaultDevhubUsername: true

      - name: "Quickbuild package"
        id: quickbuildPackage
        run: |
          sfp quickbuild --devhubalias devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/}

      - uses: navikt/sf-platform/.github/actions/uploadWorkflowArtifactsAndLogs@main
        with:
          artifactName: "build-artifacts"
          uploadArtifacts: true
          logName: "logs"
          publishLogs: true
