name: On PUSH
on:
  push:
jobs:
  staticCodeValidation:
    uses: navikt/sf-platform/.github/workflows/ciStaticCodeValidation.yml@main
  buildAndPublish:
    needs: staticCodeValidation
    uses: navikt/sf-platform/.github/workflows/buildAndPublish.yml@main
