name: Relase to Production
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Release tag
        required: false
        default: ""
      loglevel:
        description: Log level
        required: false
        type: choice
        default: INFO
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
  release:
    name: Release to Production
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:${{ vars.SFP_CONTAINER_VERSION || 'latest' }}
    permissions:
      contents: read
      packages: read
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Authenticate Node
        uses: actions/setup-node@v5
        with:
          registry-url: https://npm.pkg.github.com

      # Sets up Salesforce CLI authentication for the DevHub
      - name: Authenticate Production
        uses: navikt/sf-gha-authenticateOrg@da2f995ee865e05111574719abfc5ba12b459f0c
        with:
          auth-url: ${{ secrets.SF_DEVHUB_URL }}
          alias: prod

      - name: Release to Production
        uses: navikt/sf-gha-release@a97c935220209a3957923eb261ebb14e0660979a
        with:
          release_tag: ${{ github.event.inputs.release_tag }}
          loglevel: ${{ github.event.inputs.loglevel }}
          target_org_alias: prod
          devhub_alias: prod
          releaseNamePrefix: ${{ vars.RELEASE_NAME_PREFIX }}
          auth_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push logged metrics
        uses: navikt/sf-platform/.github/actions/pushLoggedMetrics@e0a1601b812813f88d4d3da62d75d4ee564c9a49
        with:
          metricsKey: ${{ secrets.METRICS_KEYS }}
