name: Update Package Version

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "Version number"
        required: true
        default: "1.0.0"
      package_name:
        description: "Name of the package to update"
        required: true
        default: ""

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
